# Web Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

# API 代理配置
api_proxy:
  enabled: true
  upstream: "http://localhost:8081"  # API服务器地址
  timeout: "30s"
  retry_attempts: 3

# 静态资源配置  
static:
  # 前端构建产物路径
  build_path: "./ui/dist"
  # 是否启用嵌入式资源
  embed_enabled: true
  # 缓存控制
  cache_control: "public, max-age=31536000"  # 1年
  # SPA路由支持
  spa_enabled: true
  
# 开发环境配置
development:
  # 开发服务器配置
  dev_server:
    enabled: false
    proxy_port: 3000
  # 热重载
  hot_reload: true
  # 源码映射
  source_maps: true

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    path: "./logs/web.log"
    max_size: 100
    max_backups: 3
    max_age: 28
    compress: true

# 安全配置
security:
  # 内容安全策略
  csp:
    enabled: true
    policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;"
  # HTTPS重定向
  https_redirect: false
  # 安全头
  headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"

# 监控配置
monitoring:
  metrics:
    enabled: true
    port: 9092
    path: "/metrics" 