# API Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  
grpc:
  host: "0.0.0.0"
  port: 9090
  max_connection_idle: "15m"
  max_connection_age: "30m"
  time: "5m"
  timeout: "1m"

metrics:
  enabled: true
  host: "0.0.0.0"
  port: 9091
  path: "/metrics"

database:
  type: "postgres"  # postgres, sqlite
  postgres:
    host: "localhost"
    port: 5432
    user: "singbox_user"
    password: "your_password"
    database: "singbox_web"
    sslmode: "disable"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: "1h"
    conn_max_idle_time: "30m"
  sqlite:
    file: "./data/singbox.db"
    pragma:
      - "journal_mode=WAL"
      - "synchronous=NORMAL"
      - "cache_size=1000"
      - "foreign_keys=true"

redis:
  enabled: true
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

auth:
  jwt:
    secret_key: "your-jwt-secret-key-change-in-production"
    expiration_time: "24h"
    refresh_time: "168h"  # 7 days
    issuer: "sing-box-web"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file:
    path: "./logs/api.log"
    max_size: 100  # MB
    max_backups: 3
    max_age: 28    # days
    compress: true

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Request-ID"
  expose_headers:
    - "X-Request-ID"
  allow_credentials: true
  max_age: "12h"

security:
  rate_limit:
    enabled: true
    rps: 100  # requests per second
    burst: 200
  request_size_limit: "32MB"

monitoring:
  agent:
    heartbeat_interval: "30s"
    heartbeat_timeout: "90s"
    metrics_interval: "60s"
    max_offline_duration: "300s" 