apiVersion: v1
kind: WebConfig

# Web server configuration
server:
  address: "0.0.0.0"
  port: 8080
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 60s
  tlsEnabled: false
  certFile: ""
  keyFile: ""

# Database configuration
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  database: "sing-box"
  username: "sing-box"
  password: "sing-box"
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifetime: 1h

# API server connection
apiServer:
  address: "localhost"
  port: 8081
  timeout: 10s
  insecure: true
  certFile: ""
  keyFile: ""
  caFile: ""

# Authentication configuration
auth:
  jwtSecret: "your-256-bit-secret-key-change-this-in-production"
  jwtExpiration: 24h
  refreshExpiration: 168h  # 7 days
  enableRateLimit: true
  rateLimitRequests: 100
  rateLimitDuration: 1m
  sessionTimeout: 30m
  maxConcurrentSessions: 5

# Logging configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  maxSize: 100
  maxAge: 7
  maxBackups: 3
  compress: true

# Metrics configuration
metrics:
  enabled: true
  address: "0.0.0.0"
  port: 9090
  path: "/metrics"

# SkyWalking configuration
skywalking:
  enabled: false
  collector: "localhost:11800"
  serviceName: "sing-box-web"
  sampleRate: 1