# Agent Configuration
agent:
  # 节点标识
  node_id: ""  # 空值时自动生成UUID
  node_name: ""  # 空值时使用主机名
  
  # Manager服务器配置
  manager:
    endpoint: "localhost:9090"
    tls:
      enabled: false
      cert_file: ""
      key_file: ""
      ca_file: ""
      insecure: false
    
  # 连接配置
  connection:
    dial_timeout: "10s"
    keep_alive_time: "30s"
    keep_alive_timeout: "5s"
    max_receive_message_size: "4MB"
    max_send_message_size: "4MB"
    
  # 重试配置
  retry:
    max_attempts: 5
    initial_backoff: "1s"
    max_backoff: "30s"
    backoff_multiplier: 2.0
    
  # 心跳配置
  heartbeat:
    interval: "30s"
    timeout: "10s"
    
# sing-box 控制配置
singbox:
  # sing-box 可执行文件路径
  binary_path: "/usr/local/bin/sing-box"
  
  # 配置文件路径
  config_path: "/etc/sing-box/config.json"
  
  # 工作目录
  work_dir: "/var/lib/sing-box"
  
  # 进程管理
  process:
    start_timeout: "30s"
    stop_timeout: "15s"
    restart_delay: "5s"
    max_restart_attempts: 3
    
  # 健康检查
  health_check:
    enabled: true
    interval: "60s"
    timeout: "10s"
    endpoint: "http://127.0.0.1:8080/health"  # sing-box健康检查端点
    
# 监控配置
monitoring:
  # 是否启用监控
  enabled: true
  
  # 监控数据收集间隔
  interval: "60s"
  
  # 启用的监控指标
  metrics:
    system: true      # 系统指标(CPU、内存、磁盘、网络)
    singbox: true     # sing-box指标
    process: true     # 进程指标
    
  # 系统监控配置
  system:
    # CPU监控
    cpu:
      enabled: true
      collect_per_core: false
      
    # 内存监控
    memory:
      enabled: true
      include_swap: true
      
    # 磁盘监控
    disk:
      enabled: true
      mount_points:
        - "/"
        - "/var"
      ignore_fs_types:
        - "tmpfs"
        - "devtmpfs"
        - "sysfs"
        
    # 网络监控
    network:
      enabled: true
      interfaces:
        - "eth0"
        - "wlan0"
      ignore_interfaces:
        - "lo"
        - "docker0"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    path: "./logs/agent.log"
    max_size: 100
    max_backups: 3
    max_age: 28
    compress: true

# 安全配置
security:
  # 配置文件权限
  config_permissions: "0600"
  
  # 运行用户
  run_as_user: "sing-box"
  run_as_group: "sing-box"
  
  # 配置加密
  encryption:
    enabled: false
    key_file: ""

# 本地存储配置
storage:
  # 数据目录
  data_dir: "./data"
  
  # 临时目录
  temp_dir: "./tmp"
  
  # 配置备份
  backup:
    enabled: true
    max_backups: 5
    backup_dir: "./backups"

# 通知配置
notifications:
  # 状态变更通知
  status_change: true
  
  # 错误通知
  error_notification: true
  
  # 配置更新通知
  config_update: true 